### ISSUE TITLE
Consider adding a antsibull-changelog-lint pre-commit hook 

### ISSUE THREAD

**Issue by jooola** [ansible-community/antsibull-changelog#124]
I use pre-commit to clean/format/lint projects, and I have started using it for `hetzner.hcloud`.

I would like to configure a ` antsibull-changelog lint` pre-commit hook to make sure I don't commit invalid changelog fragments.

Here is what I've started using (this could probably be improved a bit):
```yml
  - repo: local
    hooks:
      - id: antsibull-changelog-lint
        name: antsibull-changelog lint
        language: python
        additional_dependencies:
          - antsibull-changelog==0.21.0
        entry: antsibull-changelog lint
        pass_filenames: false
        files: ^changelogs/.*$
```

It would be awesome if this hook was part of the repository!
