### ISSUE TITLE
YAML indentation for change types differs from examples and expected indentation

### ISSUE THREAD

**Issue by alisonlhart** [ansible-community/antsibull-changelog#152]
Under each change type section in the generated `changelog.yml` - `bugfixes`, `major_changes`, `minor_changes`, `breaking_changes`, etc - the list of changes are placed at the same hierarchical level as the change type title. 

For example, in the `changelog.yaml` example [here](https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelog.yaml-format.md#release-information), the spacing is shown to be:
```
releases:
  1.0.0:
    release_date: '2020-04-01'
    codename: White Rabbit
    changes:
      release_summary: This is the initial White Rabbit release. Enjoy!
      major_changes:
        - The authentication method handling has been rewritten.   # Two spaces indented from `major changes`
```

In the actual generated `changelog.yaml`, all fragment details listed appear to be placed at the same indentation level as the change type. 

For example:
```
releases:
  1.0.0:
    release_date: '2020-04-01'
    codename: White Rabbit
    changes:
      release_summary: This is the initial White Rabbit release. Enjoy!
      major_changes:
      - The authentication method handling has been rewritten.   # No indention from `major changes`
```

No config.yml setting seems to have an affect on this behavior. If there's a way to prevent this behavior in the config or if this is intentional, feel free to close out this issue!
