### ISSUE TITLE
Docs for fragments / syntax?

### ISSUE THREAD

**Issue by geerlingguy** [ansible-community/antsibull-changelog#16]
I'm trying to figure out how to create a fragment in the right syntax. I know that there's a lint that can check the syntax... but it would also help if there was an example somewhere in the documentation for this project so I don't have to scour the planet looking for some representative examples.

**Comment by geerlingguy** [comment]
Just documenting for my own edification:

First, name a fragment like `GITHUB_ISSUE_NUMBER-module_name-short-description-of-change.yml`

Then add things like:

```yaml
---
minor_changes:
  - module_name_one - what was changed

bugfixes:
  - module_name_two - what was fixed
```

The full list of options below can be found in the templated `changelogs/config.yaml` file:

- `major_changes`
- `minor_changes`
- `breaking_changes`
- `deprecated_features`
- `removed_features`
- `security_fixes`
- `bugfixes`
- `known_issues`
